import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/app_controller.dart';
import '../../core/theme.dart';
import '../../core/widgets.dart';

class CommunityScreen extends StatefulWidget { const CommunityScreen({super.key}); @override State<CommunityScreen> createState()=>_CommunityScreenState(); }
class _CommunityScreenState extends State<CommunityScreen> with SingleTickerProviderStateMixin {
  late final TabController tabs;
  @override void initState(){super.initState();tabs=TabController(length:5,vsync:this);WidgetsBinding.instance.addPostFrameCallback((_){context.read<AppController>().loadCommunity();});}
  @override void dispose(){tabs.dispose();super.dispose();}
  @override Widget build(BuildContext context){final app=context.watch<AppController>();return GradientScaffold(child:NestedScrollView(headerSliverBuilder:(_,__)=>[SliverAppBar(pinned:true,backgroundColor:Colors.transparent,title:const Text('ZYNORA LIVE',style:TextStyle(fontWeight:FontWeight.w900)),bottom:TabBar(controller:tabs,isScrollable:true,tabs:const[Tab(text:'الأحداث'),Tab(text:'البطولات'),Tab(text:'اللايف'),Tab(text:'الصوت'),Tab(text:'الاقتصاد')]))],body:TabBarView(controller:tabs,children:[_Events(app),_Tournaments(app),_Live(app),_Voice(app),_Economy(app)])));}
}

class _Events extends StatelessWidget{const _Events(this.app);final AppController app;@override Widget build(BuildContext c){final all=[...app.events,...app.communityOffers];return ListView(padding:const EdgeInsets.all(16),children:[const _Hero(icon:Icons.local_fire_department_rounded,title:'أحداث وعروض ZYNORA',sub:'مهمات موسمية، عروض محدودة ومكافآت يومية.'),const SizedBox(height:14),...all.map((e)=>ZCard(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.auto_awesome)),title:Text(e['name']?.toString()??e['title']?.toString()??'عرض'),subtitle:Text(e['description']?.toString()??''))))]);}}
class _Tournaments extends StatelessWidget{const _Tournaments(this.app);final AppController app;@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const _Hero(icon:Icons.emoji_events_rounded,title:'المسابقات',sub:'بطولات بنظام نقاط وجوائز بالعملات الافتراضية.'),const SizedBox(height:14),...app.tournaments.map((t)=>ZCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(t['name']?.toString()??'Tournament',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))),Text('${t['prize_pool']??0} 🪙')]),const SizedBox(height:8),Text('${t['game_name']??''} • ${t['players']??0}/${t['max_players']??0} لاعب'),const SizedBox(height:12),PrimaryButton(label:'انضم الآن • ${t['entry_fee']??0} 🪙',icon:Icons.login_rounded,onPressed:()=>app.joinTournament(t['id'].toString()))])))]);}
class _Live extends StatelessWidget{const _Live(this.app);final AppController app;@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const _Hero(icon:Icons.live_tv_rounded,title:'قاعات LIVE',sub:'بث مباشر، هدايا متعددة الأسعار وتفاعل لحظي.'),const SizedBox(height:14),...app.liveRooms.map((r)=>ZCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.circle,color:Colors.red,size:12),const SizedBox(width:8),Expanded(child:Text(r['title']?.toString()??'ZYNORA Live',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))),Text('${r['viewer_count']??0} 👁')]),const SizedBox(height:6),Text('بث مباشر بواسطة ${r['username']??''}'),const SizedBox(height:12),Wrap(spacing:8,children:app.gifts.take(6).map((g)=>ActionChip(label:Text('${g['emoji']??'🎁'} ${g['price']??0}'),onPressed:()=>app.sendLiveGift(r['id'].toString(),g['id'].toString()))).toList())])))]);}
class _Voice extends StatelessWidget{const _Voice(this.app);final AppController app;@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[const Expanded(child:_Hero(icon:Icons.mic_rounded,title:'غرف صوتية',sub:'دردشة صوتية اجتماعية أثناء اللعب.')),IconButton.filled(onPressed:()=>app.createVoiceRoom('ZYNORA Lounge'),icon:const Icon(Icons.add_rounded))]),const SizedBox(height:14),...app.voiceRooms.map((r)=>ZCard(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.graphic_eq_rounded)),title:Text(r['name']?.toString()??'Lounge'),subtitle:Text('${r['members']??0} متصل • حتى ${r['max_speakers']??8} متحدثين'),trailing:FilledButton(onPressed:()=>app.joinVoiceRoom(r['id'].toString()),child:const Text('دخول')))))]);}
class _Economy extends StatelessWidget{const _Economy(this.app);final AppController app;@override Widget build(BuildContext c){final s=app.economyStats;return ListView(padding:const EdgeInsets.all(16),children:[const _Hero(icon:Icons.account_balance_wallet_rounded,title:'المحفظة والاقتصاد',sub:'تتبع الأرباح والمصروفات والهدايا والمنافسات الافتراضية.'),const SizedBox(height:14),Row(children:[Expanded(child:_Metric('الرصيد','${app.user?['coins']??0} 🪙')),Expanded(child:_Metric('أرباح المنافسات','${s['winnings']??0} 🪙'))]),const SizedBox(height:10),Row(children:[Expanded(child:_Metric('المصروف','${s['spent_on_matches']??0} 🪙')),Expanded(child:_Metric('الصافي','${s['net']??0} 🪙'))]),const SizedBox(height:12),...app.economyLedger.map((x)=>ListTile(leading:Icon((x['amount']??0)>=0?Icons.arrow_downward_rounded:Icons.arrow_upward_rounded),title:Text(x['note']?.toString()??x['kind']?.toString()??''),subtitle:Text(x['created_at']?.toString()??''),trailing:Text('${x['amount']??0}'))) ]);}}
class _Metric extends StatelessWidget{const _Metric(this.title,this.value);final String title,value;@override Widget build(BuildContext c)=>ZCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:Colors.white.withValues(alpha: .6))),const SizedBox(height:5),Text(value,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:20,color:ZTheme.gold))]));}
class _Hero extends StatelessWidget{const _Hero({required this.icon,required this.title,required this.sub});final IconData icon;final String title,sub;@override Widget build(BuildContext c)=>Row(children:[Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(shape:BoxShape.circle,color:ZTheme.gold.withValues(alpha: .12)),child:Icon(icon,color:ZTheme.gold)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:20)),Text(sub,style:TextStyle(color:Colors.white.withValues(alpha: .6)))]))]);}
