import { Router } from 'express';
import { pool, query } from '../lib/db';
import { requireAuth, requireAdmin } from '../middleware/auth';
export const adminRouter=Router();
adminRouter.use(requireAuth,requireAdmin);
adminRouter.get('/summary',async(_req,res)=>{const [u,r,m,t,p,a]=await Promise.all([query('SELECT COUNT(*)::int count FROM users'),query("SELECT COUNT(*)::int count FROM rooms WHERE status='active'"),query('SELECT COUNT(*)::int count FROM matches'),query('SELECT COUNT(*)::int count FROM coins_transactions'),query("SELECT COUNT(*)::int count FROM recharge_requests WHERE status='pending'"),query('SELECT * FROM advertisements ORDER BY id')]);res.json({metrics:{users:u.rows[0].count,activeRooms:r.rows[0].count,matches:m.rows[0].count,coinTransactions:t.rows[0].count,pendingRecharges:p.rows[0].count},ads:a.rows});});
adminRouter.get('/recharges',async(_req,res)=>{const r=await query(`SELECT r.*,u.username,u.email,p.name package_name,p.coins,p.price_cents,p.currency FROM recharge_requests r JOIN users u ON u.id=r.user_id JOIN coin_packages p ON p.id=r.package_id ORDER BY r.created_at DESC LIMIT 100`);res.json({requests:r.rows});});
adminRouter.post('/recharges/:id/approve',async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`SELECT r.id,r.user_id,r.status,p.coins FROM recharge_requests r JOIN coin_packages p ON p.id=r.package_id WHERE r.id=$1 FOR UPDATE`,[String(req.params.id)]);if(!r.rowCount){await c.query('ROLLBACK');return res.status(404).json({message:'Request not found'});}if(r.rows[0].status!=='pending'){await c.query('ROLLBACK');return res.status(409).json({message:'Request already reviewed'});}await c.query('UPDATE users SET coins=coins+$2,updated_at=NOW() WHERE id=$1',[r.rows[0].user_id,r.rows[0].coins]);await c.query('INSERT INTO coins_transactions(user_id,amount,reason) VALUES($1,$2,$3)',[r.rows[0].user_id,r.rows[0].coins,`recharge:${r.rows[0].id}`]);await c.query("INSERT INTO wallet_ledger(user_id,kind,amount,balance_after,reference_type,reference_id,note) SELECT $1,'recharge',$2,coins,'recharge',$3,'Admin approved recharge' FROM users WHERE id=$1",[r.rows[0].user_id,r.rows[0].coins,r.rows[0].id]);await c.query("UPDATE recharge_requests SET status='approved',admin_note=$2,reviewed_at=NOW() WHERE id=$1",[r.rows[0].id,String(req.body?.note??'Approved')]);await c.query('COMMIT');res.json({message:'Recharge approved'});}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});
adminRouter.post('/recharges/:id/reject',async(req,res)=>{const r=await query("UPDATE recharge_requests SET status='rejected',admin_note=$2,reviewed_at=NOW() WHERE id=$1 AND status='pending' RETURNING id",[String(req.params.id),String(req.body?.note??'Rejected')]);if(!r.rowCount)return res.status(404).json({message:'Pending request not found'});res.json({message:'Recharge rejected'});});
adminRouter.post('/ads/:id/toggle',async(req,res)=>{const r=await query('UPDATE advertisements SET enabled=NOT enabled WHERE id=$1 RETURNING *',[String(req.params.id)]);if(!r.rowCount)return res.status(404).json({message:'Ad not found'});res.json({ad:r.rows[0]});});
adminRouter.get('/community',async(_req,res)=>{
  const [events,offers,tournaments,gifts,live,voice]=await Promise.all([
    query('SELECT * FROM events ORDER BY start_date DESC NULLS LAST'),
    query('SELECT * FROM offers ORDER BY starts_at DESC NULLS LAST'),
    query('SELECT t.*,g.name AS game_name FROM tournaments t JOIN games g ON g.id=t.game_id ORDER BY t.starts_at DESC NULLS LAST'),
    query('SELECT * FROM gifts ORDER BY price'),
    query(`SELECT l.*,u.username FROM live_rooms l JOIN users u ON u.id=l.host_user_id ORDER BY l.started_at DESC`),
    query(`SELECT v.*,u.username FROM voice_rooms v JOIN users u ON u.id=v.host_user_id ORDER BY v.created_at DESC`)
  ]);
  res.json({events:events.rows,offers:offers.rows,tournaments:tournaments.rows,gifts:gifts.rows,liveRooms:live.rows,voiceRooms:voice.rows});
});
adminRouter.post('/offers/:id/toggle',async(req,res)=>{const r=await query('UPDATE offers SET enabled=NOT enabled WHERE id=$1 RETURNING *',[String(req.params.id)]);if(!r.rowCount)return res.status(404).json({message:'Offer not found'});res.json({offer:r.rows[0]});});
adminRouter.post('/tournaments/:id/status',async(req,res)=>{const status=String(req.body?.status??'upcoming');if(!['upcoming','open','live','finished','cancelled'].includes(status))return res.status(400).json({message:'Invalid status'});const r=await query('UPDATE tournaments SET status=$2 WHERE id=$1 RETURNING *',[String(req.params.id),status]);if(!r.rowCount)return res.status(404).json({message:'Tournament not found'});res.json({tournament:r.rows[0]});});
adminRouter.post('/gifts/:id/toggle',async(req,res)=>{const r=await query('UPDATE gifts SET enabled=NOT enabled WHERE id=$1 RETURNING *',[String(req.params.id)]);if(!r.rowCount)return res.status(404).json({message:'Gift not found'});res.json({gift:r.rows[0]});});
adminRouter.post('/live/:id/end',async(req,res)=>{const r=await query(`UPDATE live_rooms SET status='ended',ended_at=NOW() WHERE id=$1 AND status='live' RETURNING *`,[String(req.params.id)]);if(!r.rowCount)return res.status(404).json({message:'Live room not found'});res.json({room:r.rows[0]});});
adminRouter.post('/voice-rooms/:id/close',async(req,res)=>{const r=await query(`UPDATE voice_rooms SET status='closed' WHERE id=$1 AND status='open' RETURNING *`,[String(req.params.id)]);if(!r.rowCount)return res.status(404).json({message:'Voice room not found'});res.json({room:r.rows[0]});});
